from PyQt5 import QtCore, QtGui, QtWidgets
import resources

class Ui_AccountWindow(object):
    def __init__(self, parent=None):  # * for window trans
        self.parent = parent
    def setupUi(self, AccountWindow):
        self.AccountWindow = AccountWindow
        AccountWindow.setObjectName("AccountWindow")
        AccountWindow.resize(500, 350)
        AccountWindow.setMinimumSize(QtCore.QSize(500, 350))
        AccountWindow.setMaximumSize(QtCore.QSize(500, 350))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/spotify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AccountWindow.setWindowIcon(icon)
        AccountWindow.setStyleSheet("background-image: url(:/Background/background/darkgreen.png);\n"
"")
        self.gridLayout_2 = QtWidgets.QGridLayout(AccountWindow)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.concertList_btn = QtWidgets.QPushButton(AccountWindow)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.concertList_btn.setFont(font)
        self.concertList_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.concertList_btn.setObjectName("concertList_btn")
        self.gridLayout_2.addWidget(self.concertList_btn, 4, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 10, 1, 1, 1)
        self.MusicList_btn = QtWidgets.QPushButton(AccountWindow)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.MusicList_btn.setFont(font)
        self.MusicList_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.MusicList_btn.setObjectName("MusicList_btn")
        self.gridLayout_2.addWidget(self.MusicList_btn, 7, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.return_btn = QtWidgets.QPushButton(AccountWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.return_btn.setFont(font)
        self.return_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.return_btn.setObjectName("return_btn")
        self.gridLayout_2.addWidget(self.return_btn, 9, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 4, 4, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.balance_lbl = QtWidgets.QLabel(AccountWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.balance_lbl.setFont(font)
        self.balance_lbl.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n"
"color: rgb(255, 255, 255);")
        self.balance_lbl.setObjectName("balance_lbl")
        self.verticalLayout_2.addWidget(self.balance_lbl)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.deposit_btn = QtWidgets.QPushButton(AccountWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.deposit_btn.setFont(font)
        self.deposit_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.deposit_btn.setObjectName("deposit_btn")
        self.horizontalLayout.addWidget(self.deposit_btn)
        self.deposit_lineEdit = QtWidgets.QLineEdit(AccountWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deposit_lineEdit.sizePolicy().hasHeightForWidth())
        self.deposit_lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.deposit_lineEdit.setFont(font)
        self.deposit_lineEdit.setStyleSheet("background-image: url(:/Background/background/transparent.png);")
        self.deposit_lineEdit.setObjectName("deposit_lineEdit")
        self.horizontalLayout.addWidget(self.deposit_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 4, 0, 1, 1)
        self.tickets_btn = QtWidgets.QPushButton(AccountWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tickets_btn.setFont(font)
        self.tickets_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.tickets_btn.setObjectName("tickets_btn")
        self.gridLayout_2.addWidget(self.tickets_btn, 9, 1, 1, 1)
        self.artist_checkBox = QtWidgets.QCheckBox(AccountWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.artist_checkBox.setFont(font)
        self.artist_checkBox.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n"
"color: rgb(255, 255, 255);")
        self.artist_checkBox.setObjectName("artist_checkBox")
        self.gridLayout_2.addWidget(self.artist_checkBox, 3, 3, 1, 1)
        self.Friends_btn = QtWidgets.QPushButton(AccountWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Friends_btn.setFont(font)
        self.Friends_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.Friends_btn.setObjectName("Friends_btn")
        self.gridLayout_2.addWidget(self.Friends_btn, 3, 1, 1, 1)
        self.following_btn = QtWidgets.QPushButton(AccountWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.following_btn.setFont(font)
        self.following_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.following_btn.setObjectName("following_btn")
        self.gridLayout_2.addWidget(self.following_btn, 4, 1, 1, 1)
        self.follower_btn = QtWidgets.QPushButton(AccountWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.follower_btn.setFont(font)
        self.follower_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.follower_btn.setObjectName("follower_btn")
        self.gridLayout_2.addWidget(self.follower_btn, 7, 1, 1, 1)

        self.retranslateUi(AccountWindow)
        QtCore.QMetaObject.connectSlotsByName(AccountWindow)

        self.return_btn.clicked.connect(self.open_parent_window)
    def open_parent_window(self):
        self.parent.show()
        self.AccountWindow.close()

    def retranslateUi(self, AccountWindow):
        _translate = QtCore.QCoreApplication.translate
        AccountWindow.setWindowTitle(_translate("AccountWindow", "Account"))
        self.concertList_btn.setText(_translate("AccountWindow", "Concert List"))
        self.MusicList_btn.setText(_translate("AccountWindow", "Musics List"))
        self.return_btn.setText(_translate("AccountWindow", "Return"))
        self.balance_lbl.setText(_translate("AccountWindow", "Balance:9999999"))
        self.deposit_btn.setText(_translate("AccountWindow", "Deposit"))
        self.deposit_lineEdit.setPlaceholderText(_translate("AccountWindow", "Enter desired amount"))
        self.tickets_btn.setText(_translate("AccountWindow", "Tickets"))
        self.artist_checkBox.setText(_translate("AccountWindow", "Artist"))
        self.Friends_btn.setText(_translate("AccountWindow", "Friends"))
        self.following_btn.setText(_translate("AccountWindow", "Following"))
        self.follower_btn.setText(_translate("AccountWindow", "Follower"))
