import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets
import resources
from dbfunctions import *
from DBManagement import DBM
from datatype import *


class Ui_SearchWindow(object):
    def __init__(self, parent=None , appstate=None):
        self.parent = parent
        self.appstate = appstate

    def setupUi(self, SearchWindow):
        self.SearchWindow = SearchWindow
        SearchWindow.setObjectName("SearchWindow")
        SearchWindow.resize(342, 352)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SearchWindow.sizePolicy().hasHeightForWidth())
        SearchWindow.setSizePolicy(sizePolicy)
        SearchWindow.setMinimumSize(QtCore.QSize(342, 352))
        SearchWindow.setMaximumSize(QtCore.QSize(342, 352))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/spotify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SearchWindow.setWindowIcon(icon)
        SearchWindow.setStyleSheet("background-image: url(:/Background/background/darkgreen.png);")
        self.gridLayout = QtWidgets.QGridLayout(SearchWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Title_lbl = QtWidgets.QLabel(SearchWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Title_lbl.setFont(font)
        self.Title_lbl.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n""color: rgb(255, 255, 255);")
        self.Title_lbl.setObjectName("Title_lbl")
        self.horizontalLayout.addWidget(self.Title_lbl)
        self.title_lineEdit = QtWidgets.QLineEdit(SearchWindow)
        self.title_lineEdit.setMaximumSize(QtCore.QSize(265, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.title_lineEdit.setFont(font)
        self.title_lineEdit.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n""")
        self.title_lineEdit.setObjectName("title_lineEdit")
        self.horizontalLayout.addWidget(self.title_lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Genre_lbl = QtWidgets.QLabel(SearchWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Genre_lbl.setFont(font)
        self.Genre_lbl.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n""color: rgb(255, 255, 255);")
        self.Genre_lbl.setObjectName("Genre_lbl")
        self.horizontalLayout_5.addWidget(self.Genre_lbl)
        self.Genre_lineEdit = QtWidgets.QLineEdit(SearchWindow)
        self.Genre_lineEdit.setMaximumSize(QtCore.QSize(265, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Genre_lineEdit.setFont(font)
        self.Genre_lineEdit.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n""")
        self.Genre_lineEdit.setObjectName("Genre_lineEdit")
        self.horizontalLayout_5.addWidget(self.Genre_lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Artist_lbl = QtWidgets.QLabel(SearchWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Artist_lbl.setFont(font)
        self.Artist_lbl.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n""color: rgb(255, 255, 255);")
        self.Artist_lbl.setObjectName("Artist_lbl")
        self.horizontalLayout_2.addWidget(self.Artist_lbl)
        self.Artist_lineEdit = QtWidgets.QLineEdit(SearchWindow)
        self.Artist_lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.Artist_lineEdit.setMaximumSize(QtCore.QSize(265, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Artist_lineEdit.setFont(font)
        self.Artist_lineEdit.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n""")
        self.Artist_lineEdit.setObjectName("Artist_lineEdit")
        self.horizontalLayout_2.addWidget(self.Artist_lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Age_lbl = QtWidgets.QLabel(SearchWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Age_lbl.setFont(font)
        self.Age_lbl.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n""color: rgb(255, 255, 255);")
        self.Age_lbl.setObjectName("Age_lbl")
        self.horizontalLayout_3.addWidget(self.Age_lbl)
        self.Genre_lineEdit_2 = QtWidgets.QLineEdit(SearchWindow)
        self.Genre_lineEdit_2.setMinimumSize(QtCore.QSize(0, 0))
        self.Genre_lineEdit_2.setMaximumSize(QtCore.QSize(265, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Genre_lineEdit_2.setFont(font)
        self.Genre_lineEdit_2.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n""")
        self.Genre_lineEdit_2.setObjectName("Genre_lineEdit_2")
        self.horizontalLayout_3.addWidget(self.Genre_lineEdit_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Area_lbl = QtWidgets.QLabel(SearchWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Area_lbl.setFont(font)
        self.Area_lbl.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n""color: rgb(255, 255, 255);")
        self.Area_lbl.setObjectName("Area_lbl")
        self.horizontalLayout_4.addWidget(self.Area_lbl)
        self.Area_lineEdit = QtWidgets.QLineEdit(SearchWindow)
        self.Area_lineEdit.setMaximumSize(QtCore.QSize(265, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Area_lineEdit.setFont(font)
        self.Area_lineEdit.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n""")
        self.Area_lineEdit.setObjectName("Area_lineEdit")
        self.horizontalLayout_4.addWidget(self.Area_lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.back_btn = QtWidgets.QPushButton(SearchWindow)
        self.back_btn.setStyleSheet("color: rgb(255, 255, 255);\n""background-color: rgb(0, 0, 0);")
        self.back_btn.setObjectName("back_btn")
        self.horizontalLayout_6.addWidget(self.back_btn)
        self.search_btn = QtWidgets.QPushButton(SearchWindow)
        self.search_btn.setStyleSheet("color: rgb(255, 255, 255);\n""background-color: rgb(0, 0, 0);")
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout_6.addWidget(self.search_btn)
        self.gridLayout.addLayout(self.horizontalLayout_6, 5, 0, 1, 1)
        self.retranslateUi(SearchWindow)
        QtCore.QMetaObject.connectSlotsByName(SearchWindow)

        #$ My Part --------------------------------------------
        self.back_btn.clicked.connect(self.open_parent_window)
        self.search_btn.clicked.connect(self.search)
    def search(self):
        title = self.title_lineEdit.text()
        genre = self.Genre_lineEdit.text()
        artist = self.Artist_lineEdit.text()
        age = self.Genre_lineEdit_2.text()
        area = self.Area_lineEdit.text()
        dbm = DBM()
        dbm.db_connect()
        result =search(dbm,title,artist,genre,age,area)
        if result is None or len(result)==0:
            #show qt message box
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Warning)
            msg.setText("No result found")
            msg.setWindowTitle("Search")
            msg.exec_()
            return
        #show result qt message box
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Information)
        msg.setText("Search result")
        msg.setWindowTitle("Search")
        msg.setDetailedText(str(result))# later show the result in a better way
        msg.exec_()
        
            
            
            
            

    def retranslateUi(self, SearchWindow):
        _translate = QtCore.QCoreApplication.translate
        SearchWindow.setWindowTitle(_translate("SearchWindow", "Search"))
        self.Title_lbl.setText(_translate("SearchWindow", "Title"))
        self.Genre_lbl.setText(_translate("SearchWindow", "Genre"))
        self.Artist_lbl.setText(_translate("SearchWindow", "Artist"))
        self.Age_lbl.setText(_translate("SearchWindow", "Age"))
        self.Area_lbl.setText(_translate("SearchWindow", "Area"))
        self.back_btn.setText(_translate("SearchWindow", "Back"))
        self.search_btn.setText(_translate("SearchWindow", "Search"))

    def open_parent_window(self):
        self.parent.show()
        self.SearchWindow.close()
