# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\MRM.TFW\Desktop\pyproj\SendMsg.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SendmsgWindow(object):
    def setupUi(self, SendmsgWindow):
        SendmsgWindow.setObjectName("SendmsgWindow")
        SendmsgWindow.resize(500, 487)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/spotify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SendmsgWindow.setWindowIcon(icon)
        SendmsgWindow.setStyleSheet("background-image: url(:/Background/background/darkgreen.png);")
        self.verticalLayout = QtWidgets.QVBoxLayout(SendmsgWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.msgs_lbl = QtWidgets.QLabel(SendmsgWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.msgs_lbl.setFont(font)
        self.msgs_lbl.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n"
"color: rgb(255, 255, 255);")
        self.msgs_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.msgs_lbl.setObjectName("msgs_lbl")
        self.verticalLayout.addWidget(self.msgs_lbl)
        self.msgs_listView = QtWidgets.QListView(SendmsgWindow)
        self.msgs_listView.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.msgs_listView.setObjectName("msgs_listView")
        self.verticalLayout.addWidget(self.msgs_listView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Friends_lbl = QtWidgets.QLabel(SendmsgWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Friends_lbl.setFont(font)
        self.Friends_lbl.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n"
"color: rgb(255, 255, 255);")
        self.Friends_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.Friends_lbl.setObjectName("Friends_lbl")
        self.verticalLayout_2.addWidget(self.Friends_lbl)
        self.friends_listView = QtWidgets.QListView(SendmsgWindow)
        self.friends_listView.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.friends_listView.setObjectName("friends_listView")
        self.verticalLayout_2.addWidget(self.friends_listView)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.msg_textEdit = QtWidgets.QTextEdit(SendmsgWindow)
        self.msg_textEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.msg_textEdit.setFont(font)
        self.msg_textEdit.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.msg_textEdit.setObjectName("msg_textEdit")
        self.horizontalLayout.addWidget(self.msg_textEdit)
        self.SendMsg_btn = QtWidgets.QPushButton(SendmsgWindow)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.SendMsg_btn.setFont(font)
        self.SendMsg_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.SendMsg_btn.setObjectName("SendMsg_btn")
        self.horizontalLayout.addWidget(self.SendMsg_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Back_btn = QtWidgets.QPushButton(SendmsgWindow)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Back_btn.setFont(font)
        self.Back_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.Back_btn.setObjectName("Back_btn")
        self.horizontalLayout_2.addWidget(self.Back_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(SendmsgWindow)
        QtCore.QMetaObject.connectSlotsByName(SendmsgWindow)

    def retranslateUi(self, SendmsgWindow):
        _translate = QtCore.QCoreApplication.translate
        SendmsgWindow.setWindowTitle(_translate("SendmsgWindow", "Send Message"))
        self.msgs_lbl.setText(_translate("SendmsgWindow", "Messages"))
        self.Friends_lbl.setText(_translate("SendmsgWindow", "Friends list"))
        self.msg_textEdit.setPlaceholderText(_translate("SendmsgWindow", "Write message"))
        self.SendMsg_btn.setText(_translate("SendmsgWindow", "Send Msg"))
        self.Back_btn.setText(_translate("SendmsgWindow", "Back"))
import main_rc
