from PyQt5 import QtCore, QtGui, QtWidgets
import resources
from dbfunctions import *
from DBManagement import DBM


class Ui_SignupWindow(object):
    def __init__(self, login_signup=None, appstate=None):
        self.login_signup = login_signup
        self.appstate = appstate

    def setupUi(self, SignupWindow):
        self.SignupWindow = SignupWindow
        SignupWindow.setObjectName("SignupWindow")
        SignupWindow.resize(500, 541)
        SignupWindow.setStyleSheet("background-image: url(:/Background/background/darkgreen.png);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/spotify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SignupWindow.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(SignupWindow)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LName_lineEdit = QtWidgets.QLineEdit(SignupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LName_lineEdit.sizePolicy().hasHeightForWidth())
        self.LName_lineEdit.setSizePolicy(sizePolicy)
        self.LName_lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.LName_lineEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LName_lineEdit.setFont(font)
        self.LName_lineEdit.setStyleSheet("background-image: url(:/Background/background/transparent.png);")
        self.LName_lineEdit.setObjectName("LName_lineEdit")
        self.gridLayout_2.addWidget(self.LName_lineEdit, 5, 1, 1, 1)
        self.Email_lineEdit = QtWidgets.QLineEdit(SignupWindow)
        self.Email_lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.Email_lineEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Email_lineEdit.setFont(font)
        self.Email_lineEdit.setStyleSheet("background-image: url(:/Background/background/transparent.png);")
        self.Email_lineEdit.setObjectName("Email_lineEdit")
        self.gridLayout_2.addWidget(self.Email_lineEdit, 6, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 7, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.SignUp_icon = QtWidgets.QLabel(SignupWindow)
        self.SignUp_icon.setEnabled(True)
        self.SignUp_icon.setMinimumSize(QtCore.QSize(50, 51))
        self.SignUp_icon.setMaximumSize(QtCore.QSize(50, 51))
        self.SignUp_icon.setStyleSheet("background-image: url(:/Icons/Icons/signup.png);")
        self.SignUp_icon.setText("")
        self.SignUp_icon.setObjectName("SignUp_icon")
        self.horizontalLayout_3.addWidget(self.SignUp_icon)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.Password_lineEdit = QtWidgets.QLineEdit(SignupWindow)
        self.Password_lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.Password_lineEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Password_lineEdit.setFont(font)
        self.Password_lineEdit.setStyleSheet("background-image: url(:/Background/background/transparent.png);")
        self.Password_lineEdit.setObjectName("Password_lineEdit")
        self.gridLayout_2.addWidget(self.Password_lineEdit, 9, 1, 1, 1)
        self.Name_lineEdit = QtWidgets.QLineEdit(SignupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Name_lineEdit.sizePolicy().hasHeightForWidth())
        self.Name_lineEdit.setSizePolicy(sizePolicy)
        self.Name_lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.Name_lineEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Name_lineEdit.setFont(font)
        self.Name_lineEdit.setStyleSheet("background-image: url(:/Background/background/transparent.png);")
        self.Name_lineEdit.setObjectName("Name_lineEdit")
        self.gridLayout_2.addWidget(self.Name_lineEdit, 4, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Address_label = QtWidgets.QLabel(SignupWindow)
        self.Address_label.setMinimumSize(QtCore.QSize(0, 70))
        self.Address_label.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Address_label.setFont(font)
        self.Address_label.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n""color: rgb(255, 255, 255);\n""")
        self.Address_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Address_label.setObjectName("Address_label")
        self.horizontalLayout.addWidget(self.Address_label)
        self.Address_lineEdit = QtWidgets.QTextEdit(SignupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Address_lineEdit.sizePolicy().hasHeightForWidth())
        self.Address_lineEdit.setSizePolicy(sizePolicy)
        self.Address_lineEdit.setMinimumSize(QtCore.QSize(0, 70))
        self.Address_lineEdit.setMaximumSize(QtCore.QSize(16777215, 70))
        self.Address_lineEdit.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n""background-color: rgb(255, 255, 255);")
        self.Address_lineEdit.setObjectName("Address_lineEdit")
        self.horizontalLayout.addWidget(self.Address_lineEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout, 7, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.back_btn = QtWidgets.QPushButton(SignupWindow)
        self.back_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.back_btn.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.back_btn.setFont(font)
        self.back_btn.setStyleSheet("color: rgb(255, 255, 255);\n""border-image: url(:/Background/background/darkgreen.png);")
        self.back_btn.setObjectName("back_btn")
        self.horizontalLayout_2.addWidget(self.back_btn)
        self.signup_btn = QtWidgets.QPushButton(SignupWindow)
        self.signup_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.signup_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.signup_btn.setFont(font)
        self.signup_btn.setStyleSheet("color: rgb(255, 255, 255);\n""border-image: url(:/Background/background/darkgreen.png);")
        self.signup_btn.setObjectName("signup_btn")
        self.horizontalLayout_2.addWidget(self.signup_btn)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 12, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 7, 0, 1, 1)
        self.Username_lineEdit = QtWidgets.QLineEdit(SignupWindow)
        self.Username_lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.Username_lineEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Username_lineEdit.setFont(font)
        self.Username_lineEdit.setStyleSheet("background-image: url(:/Background/background/transparent.png);")
        self.Username_lineEdit.setObjectName("Username_lineEdit")
        self.gridLayout_2.addWidget(self.Username_lineEdit, 8, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 13, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 0, 1, 1, 1)
        self.retranslateUi(SignupWindow)
        QtCore.QMetaObject.connectSlotsByName(SignupWindow)

        #$ My Part --------------------------------------------
        self.back_btn.clicked.connect(self.open_parent_window)
        self.signup_btn.clicked.connect(self.register_user)

    def retranslateUi(self, SignupWindow):
        _translate = QtCore.QCoreApplication.translate
        SignupWindow.setWindowTitle(_translate("SignupWindow", "Signup"))
        self.back_btn.setText(_translate("SignupWindow", "Back"))
        self.Name_lineEdit.setPlaceholderText(_translate("SignupWindow", "Name"))
        self.LName_lineEdit.setPlaceholderText(_translate("SignupWindow", "Last name"))
        self.Email_lineEdit.setPlaceholderText(_translate("SignupWindow", "Email"))
        self.Address_label.setText(_translate("SignupWindow", "Address"))
        self.Username_lineEdit.setPlaceholderText(_translate("SignupWindow", "Username"))
        self.Password_lineEdit.setPlaceholderText(_translate("SignupWindow", "Password"))
        self.signup_btn.setText(_translate("SignupWindow", "Sign Up"))


    def open_parent_window(self):
        self.login_signup.show()
        self.SignupWindow.close()

    def register_user(self):
        dbm = DBM()
        dbm.db_connect()
        resultBool = insert_one_user(
            dbm,
            self.Name_lineEdit.text(),
            self.LName_lineEdit.text(),
            self.Email_lineEdit.text(),
            self.Address_lineEdit.toPlainText(),
            self.Username_lineEdit.text(),
            self.Password_lineEdit.text()
        ) 
        dbm.db_disconnect()
        if resultBool:
            print("User registered successfully")
            self.Name_lineEdit.clear()
            self.LName_lineEdit.clear()
            self.Email_lineEdit.clear()
            self.Address_lineEdit.clear()
            self.Username_lineEdit.clear()
            self.Password_lineEdit.clear()
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Information)
            msg.setText("User registered successfully")
            msg.setWindowTitle("Success")
            msg.exec_()
            self.open_parent_window()
        else:
            print("User registration failed")
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Critical)
            msg.setText("User registration failed")
            msg.setWindowTitle("Error")
            msg.exec_()
           