from PyQt5 import QtCore, QtGui, QtWidgets
from DBManagement import DBM
from dbfunctions import *
import sqlite3

class Ui_FriendsWindow(object):
    def __init__(self, parent=None , appstate=None):
        self.parent = parent
        self.appstate = appstate

    def setupUi(self, FriendsWindow):
        self.FriendsWindow = FriendsWindow
        FriendsWindow.setObjectName("FriendsWindow")
        FriendsWindow.resize(600, 800)
        FriendsWindow.setMinimumSize(QtCore.QSize(600, 800))
        FriendsWindow.setMaximumSize(QtCore.QSize(600, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/spotify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FriendsWindow.setWindowIcon(icon)
        FriendsWindow.setStyleSheet("background-image: url(:/Background/background/darkgreen.png);")
        self.gridLayout = QtWidgets.QGridLayout(FriendsWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.Friends_listView = QtWidgets.QListView(FriendsWindow)
        self.Friends_listView.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n""color: rgb(0, 0, 0);\n""background-color: rgb(255, 255, 255);")
        self.Friends_listView.setObjectName("Friends_listView")
        self.gridLayout.addWidget(self.Friends_listView, 4, 0, 1, 1)
        self.Requests_lbl = QtWidgets.QLabel(FriendsWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Requests_lbl.setFont(font)
        self.Requests_lbl.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n""color: rgb(255, 255, 255);")
        self.Requests_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.Requests_lbl.setObjectName("Requests_lbl")
        self.gridLayout.addWidget(self.Requests_lbl, 1, 0, 1, 1)
        self.FriendsList_label = QtWidgets.QLabel(FriendsWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.FriendsList_label.setFont(font)
        self.FriendsList_label.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n""color: rgb(255, 255, 255);")
        self.FriendsList_label.setAlignment(QtCore.Qt.AlignCenter)
        self.FriendsList_label.setObjectName("FriendsList_label")
        self.gridLayout.addWidget(self.FriendsList_label, 3, 0, 1, 1)
        self.Messages_tableView = QtWidgets.QListView(FriendsWindow)
        self.Messages_tableView.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n""color: rgb(0, 0, 0);\n""background-color: rgb(255, 255, 255);")
        self.Messages_tableView.setObjectName("Messages_tableView")
        self.gridLayout.addWidget(self.Messages_tableView, 2, 1, 1, 1)
        self.Messages_lbl = QtWidgets.QLabel(FriendsWindow)
        self.Messages_lbl.setMinimumSize(QtCore.QSize(300, 0))
        self.Messages_lbl.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Messages_lbl.setFont(font)
        self.Messages_lbl.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n""color: rgb(255, 255, 255);")
        self.Messages_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.Messages_lbl.setObjectName("Messages_lbl")
        self.gridLayout.addWidget(self.Messages_lbl, 1, 1, 1, 1)
        self.Report_lbl = QtWidgets.QLabel(FriendsWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Report_lbl.setFont(font)
        self.Report_lbl.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n""color: rgb(255, 255, 255);")
        self.Report_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.Report_lbl.setObjectName("Report_lbl")
        self.gridLayout.addWidget(self.Report_lbl, 3, 1, 1, 1)
        self.Reject_listView = QtWidgets.QListView(FriendsWindow)
        self.Reject_listView.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n""color: rgb(0, 0, 0);\n""background-color: rgb(255, 255, 255);")
        self.Reject_listView.setObjectName("Reject_listView")
        self.gridLayout.addWidget(self.Reject_listView, 4, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Sendreq_lineEdit = QtWidgets.QLineEdit(FriendsWindow)
        self.Sendreq_lineEdit.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n""")
        self.Sendreq_lineEdit.setObjectName("Sendreq_lineEdit")
        self.horizontalLayout_2.addWidget(self.Sendreq_lineEdit)
        self.Sendreq_btn = QtWidgets.QPushButton(FriendsWindow)
        self.Sendreq_btn.setStyleSheet("color: rgb(255, 255, 255);\n""background-color: rgb(0, 0, 0);")
        self.Sendreq_btn.setObjectName("Sendreq_btn")
        self.horizontalLayout_2.addWidget(self.Sendreq_btn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.Requests_listView = QtWidgets.QListView(FriendsWindow)
        self.Requests_listView.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n""color: rgb(0, 0, 0);\n""background-color: rgb(255, 255, 255);")
        self.Requests_listView.setObjectName("Requests_listView")
        self.gridLayout.addWidget(self.Requests_listView, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.back_btn = QtWidgets.QPushButton(FriendsWindow)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.back_btn.setFont(font)
        self.back_btn.setStyleSheet("color: rgb(255, 255, 255);\n""background-color: rgb(0, 0, 0);")
        self.back_btn.setObjectName("back_btn")
        self.horizontalLayout.addWidget(self.back_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 9, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Msg_lineEdit = QtWidgets.QLineEdit(FriendsWindow)
        self.Msg_lineEdit.setStyleSheet("background-image: url(:/Background/background/transparent.png);\n""")
        self.Msg_lineEdit.setObjectName("Msg_lineEdit")
        self.horizontalLayout_3.addWidget(self.Msg_lineEdit)
        self.SendMsg_btn = QtWidgets.QPushButton(FriendsWindow)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SendMsg_btn.setFont(font)
        self.SendMsg_btn.setStyleSheet("color: rgb(255, 255, 255);\n""background-color: rgb(0, 0, 0);")
        self.SendMsg_btn.setObjectName("SendMsg_btn")
        self.horizontalLayout_3.addWidget(self.SendMsg_btn)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 0, 1, 1)
        self.retranslateUi(FriendsWindow)
        QtCore.QMetaObject.connectSlotsByName(FriendsWindow)

        #$ My Part --------------------------------------------
        dbm = DBM()
        dbm.db_connect()
        friends_id = get_friends(dbm, self.appstate["userid"])
        friends_list = QtCore.QStringListModel()
        friends_list.setStringList([str(id) for id in friends_id])
        self.Friends_listView.setModel(friends_list)

        requests_id = get_requests(dbm, self.appstate["userid"])
        requests_list = QtCore.QStringListModel()
        requests_list.setStringList([str(id[0]) for id in requests_id])
        self.Requests_listView.setModel(requests_list)

        reject_id = get_rejects(dbm, self.appstate["userid"])
        reject_list = QtCore.QStringListModel()
        reject_list.setStringList([str(id[0]) for id in reject_id])
        self.Reject_listView.setModel(reject_list)

        self.Requests_listView.clicked.connect(self.accept_req)
        self.Requests_listView.doubleClicked.connect(self.reject_req)
        self.back_btn.clicked.connect(self.open_parent_window)
        self.Friends_listView.doubleClicked.connect(self.delete_friendFromlist)
        self.Sendreq_btn.clicked.connect(self.send_request)



    def retranslateUi(self, FriendsWindow):
        _translate = QtCore.QCoreApplication.translate
        FriendsWindow.setWindowTitle(_translate("FriendsWindow", "Friends"))
        self.Requests_lbl.setText(_translate("FriendsWindow", "Requests"))
        self.FriendsList_label.setText(_translate("FriendsWindow", "Friends List"))
        self.Messages_lbl.setText(_translate("FriendsWindow", "Messages"))
        self.Report_lbl.setText(_translate("FriendsWindow", "Report"))
        self.Sendreq_btn.setText(_translate("FriendsWindow", "Send request"))
        self.back_btn.setText(_translate("FriendsWindow", "Back"))
        self.SendMsg_btn.setText(_translate("FriendsWindow", "Send Msg"))

    def open_parent_window(self):
        self.parent.show()
        self.FriendsWindow.close()

    def delete_friendFromlist(self, index):
        dbm = DBM()
        dbm.db_connect()
        friend_name = index.data()
        friend_id=get_userid_by_username(dbm,friend_name)
        delete_friend(dbm, self.appstate["userid"], friend_id)
        friends_id = get_friends(dbm, self.appstate["userid"])
        friends_list = QtCore.QStringListModel()
        friends_list.setStringList([str(id) for id in friends_id])
        self.Friends_listView.setModel(friends_list)

    def send_request(self):
        dbm = DBM()
        dbm.db_connect()
        friend_name = self.Sendreq_lineEdit.text()
        friend_id = get_userid_by_username(dbm, friend_name)
        send_friend_request(dbm, self.appstate["userid"], friend_id)
        self.Sendreq_lineEdit.clear()

    def accept_req(self, index):
        dbm = DBM()
        dbm.db_connect()
        friend_name = index.data()
        friend_id = get_userid_by_username(dbm, friend_name)
        accept_friend_request(dbm, self.appstate["userid"], friend_id)
        requests_id = get_requests(dbm, self.appstate["userid"])
        requests_list = QtCore.QStringListModel()
        requests_list.setStringList([str(id[0]) for id in requests_id])
        self.Requests_listView.setModel(requests_list)
        friends_id = get_friends(dbm, self.appstate["userid"])
        friends_list = QtCore.QStringListModel()
        friends_list.setStringList([str(id) for id in friends_id])
        self.Friends_listView.setModel(friends_list)

    def reject_req(self, index):
        dbm = DBM()
        dbm.db_connect()
        friend_name = index.data()
        friend_id = get_userid_by_username(dbm, friend_name)
        reject_friend_request(dbm, self.appstate["userid"], friend_id)
        requests_id = get_requests(dbm, self.appstate["userid"])
        requests_list = QtCore.QStringListModel()
        requests_list.setStringList([str(id[0]) for id in requests_id])
        self.Requests_listView.setModel(requests_list)




